### ISSUE TITLE
This could be expanded pretty easily...

### ISSUE THREAD

**Issue by dead-claudia** [SimenB/node-version-check#1]
You could easily expand this within a single binary like so:

``` sh
node-version-check '>=4' # version >= 4.0
node-version-check '<6.2.3' # version >= 6.2.3
```

Just a suggestion here.

**Comment by SimenB** [comment]
Available in `2.0.0`, thanks for the suggestion! https://github.com/SimenB/node-version-check/blob/master/README.md#usage
I kept the old binaries as the shortcut is nice. 😄 

(Also available in `1.1.0` under the name `node-version-satisfies`, but I prefer to keep it the same as the package, thus the major).
