### ISSUE TITLE
Cli with argument on windows

### ISSUE THREAD

**Issue by sanemat** [SimenB/node-version-check#13]
In appveyor(windows ci), 

`"node-version-check '>=4' && eslint . || node-version-check '<4'"`
shows exit status 1
https://ci.appveyor.com/project/sanemat/generator-nm5/build/1.0.233/job/s5lh38yx2ylgotrp

`"node-version-gte-4 && eslint . || node-version-lt-4"`
works fine.
https://ci.appveyor.com/project/sanemat/generator-nm5/build/1.0.236/job/2tgxpuqa7lbsgbqn

Is this expected behavior?

**Comment by SimenB** [comment]
That's not expected, no! Can you try with `"node-version-check \">=4\" && eslint . || node-version-check \"<4\""`?

**Comment by sanemat** [comment]
Both travis-ci (ubuntu) and appveyor (windows), these work fine!

Use `node-version-check \">=4\"`
- https://travis-ci.org/pandawing/generator-nm5/builds/153797269
- https://ci.appveyor.com/project/sanemat/generator-nm5/build/1.0.244

I added eslint error commit, then this works fine
- https://travis-ci.org/pandawing/generator-nm5/builds/153799062
- https://ci.appveyor.com/project/sanemat/generator-nm5/build/1.0.245
